export const select = {
	id: true,
	profileId: true,
	name: true,
	username: true,
	location: true,
	description: true,
	imageUrl: true,
	profileCreatedAt: true,
	pinnedTweetId: true,
	isProtected: true,
	isVerified: true,
	followersCount: true,
	followingCount: true,
	tweetCount: true,
	listedCount: true,
	likeCount: true,
	urls: true,
	kol: true,
};
