services:
  database-development:
    container_name: 'database-development'
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=node_api
      - POSTGRES_PASSWORD=node_api_password
      - POSTGRES_DATABASE=node_api
    ports:
      - '5432:5432'
    volumes: 
      - database-development:/var/lib/postgresql/data
  redis-development:
    container_name: 'redis-development'
    image: redis:7.2.4
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes: 
      - redis-development:/data

volumes:
  database-development:
    driver: local
  redis-development:
    driver: local

